# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lambda-epsilon-signup-signin

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1

  # you can define service wide environment variables here
  environment:
    SECRET_KEY: ${file(./envVariables.json):SECRET_KEY}
    RDS_DB: ${file(./envVariables.json):RDS_DB}
    RDS_PORT: ${file(./envVariables.json):RDS_PORT}
    RDS_USERNAME: ${file(./envVariables.json):RDS_USERNAME}
    RDS_PASSWORD: ${file(./envVariables.json):RDS_PASSWORD}
    RDS_HOSTNAME: ${file(./envVariables.json):RDS_HOSTNAME}

functions:
  userCreate:
    handler: index.userCreate
    events:
      - httpApi:
          path: /user
          method: post

  userUpdate:
    handler: index.userUpdate
    events:
      - httpApi:
          path: /user
          method: patch

  userGet:
    handler: index.userGet
    events:
      - httpApi:
          path: /user
          method: get

  login:
    handler: index.login
    events:
      - httpApi:
          path: /login
          method: post

  interests:
    handler: index.interests
    events:
      - httpApi:
          path: /interests
          method: post

  resetPassword:
    handler: index.resetPassword
    events:
      - httpApi:
          path: /resetpassword
          method: post

  questionCreate:
    handler: index.questionCreate
    events:
      - httpApi:
          path: /question
          method: post

  view:
    handler: index.view
    events:
      - httpApi:
          path: /view
          method: post
  like:
    handler: index.like
    events:
      - httpApi:
          path: /like
          method: post

  answer:
    handler: index.answer
    events:
      - httpApi:
          path: /answer
          method: post

  comment:
    handler: index.comment
    events:
      - httpApi:
          path: /comment
          method: post

  authentication:
    handler: index.authentication


#          request:
#            parameters:
#              paths:
#                id: true